input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json
    tags => ["tcp-json"]
  }
}

filter {
  if [container][name] {
    mutate {
      add_field => {
        "docker_container" => "%{[container][name]}"
      }
    }
  }
}

output {
  if "tcp-json" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch-hot:9200"]
      index => "tcp-json-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch-hot:9200"]
      index => "logstash-%{+YYYY.MM.dd}"
    }
  }
}
